all:
	g++ -std=c++17 -O2 -Iinclude example1.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example1.out
	g++ -std=c++17 -O2 -Iinclude example2.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example2.out
	g++ -std=c++17 -O2 -Iinclude example3.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example3.out
	g++ -std=c++17 -O2 -Iinclude example4.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example4.out
	g++ -std=c++17 -O2 -Iinclude example5.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example5.out
	g++ -std=c++17 -O2 -Iinclude example6.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example6.out

example1:
	g++ -std=c++17 -O2 -Iinclude example1.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example1.out

example2:
	g++ -std=c++17 -O2 -Iinclude example2.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example2.out

example3:
	g++ -std=c++17 -O2 -Iinclude example3.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example3.out

example4:
	g++ -std=c++17 -O2 -Iinclude example4.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example4.out

example5:
	g++ -std=c++17 -O2 -Iinclude example5.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example5.out

example6:
	g++ -std=c++17 -O2 -Iinclude example6.cpp -I../include     -L../libliquid  -lliquid -lpthread -ldl -o example6.out

clear:
	rm -f *.out *.dat *.pdf
